spring:
  application:
    name: api-foro
  datasource:
    url: jdbc:postgresql://localhost:5432/api_foro
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-stacktrace: never