spring:
  application:
    name: api-foro
  datasource:
    url: jdbc:postgresql://localhost:5432/api_foro
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

server:
  error:
    include-stacktrace: never